/* Code prototype for common use  */
/*     Generated by Code_Generation toolbox of Scicos with scilab-4.1.2 */
/*     date : 12-Apr-2012 */

/* ---- Headers ---- */
#include <memory.h>
#include "machine.h"

/*----------------------------------------  Lapack messag function */
void C2F(xerbla)(SRNAME,INFO,L)
     char *SRNAME;
     int *INFO;
     long int L;
{}
void set_block_error(int err)
{
  return;
}

int get_phase_simulation()
{
  return 1;
}

void * scicos_malloc(size_t size)
{
  return malloc(size);
}

void scicos_free(void *p)
{
  free(p);
}

void do_cold_restart()
{
  return;
}

void sciprint (char *fmt)
{
  return;
}

